---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stepha27/public_html/stephaniehall.ca
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
     - /bin/cp -R styles $DEPLOYPATH