export const projectList = [
    {
      id: "85503CA0-A45E-45A7-BCD9-1376F1128BC4",
      projectName: "SFU Centre for Dialogue Website Redesign",
      projectURL: "https://www.sfu.ca/dialogue.html",
      imgURL: require("../assets/images/portfolio-tb-sfu-website.png"),
      status: "Phase One Complete, Phase Two In Progres",
      type: "Employee",
      client: "SFU Morris J. Wosk Centre for Dialogue",
      role: "Product Manager and Designer",
      launchDate: "Feb. 15, 2024",
      topSkills: "HTML | Product Management | UI Design",
      skills: [
        "HTML",
        "Product Management",
        "UI Design",
        "Team Leadership",
        "User Testing",
        "Cross-team Collaboration",
        "Change Management",
        "Training",
        "Technical Writing",
        "Project Management",
        "W3C Standards",
        "Brand Narrative",
        "Web Strategy",
        "Content Strategy",
      ],
      challenge:
        "The Centre for Dialogue underwent a period of rapid growth. A side effect of this growth was that the brand narrative had not kept up with the complexity of projects and achievements throughout the Centre. One of the ways this challenge manifested itself publicly was through the website, which had unclear user journeys to understand the Centre's mission for its various audiences.",
      solution:
        "To address this challenge, I initiated a website redesign informed by user testing.",
      roleIntro:
        "My role was to plan and lead the project through to completion.",
      roleList: [
        "Convened several stakeholder meetings throughout the process to build project buy-in, collect functionality requests, and manage expectations",
        "Developed the user testing framework to inform the redesign requirements",
        "Consolidated functionality requests and user testing input to prioritize revisions and present solutions to the executive team",
        "Created the revised site-map based on stakeholder meetings and user testing to improve user experience and overall brand trust",
        "Prioritized and delegated tasks among the communications team to execute the redesign",
        "Designed and implemented several site sections (notably the search for resources, dialogue approaches, what is dialogue, K&P, and signature events sections) to move the process forward while the team juggled several other responsibilities",
        "Envisioned and implemented cross-promotional features to encourage deeper engagement with the site's content and to  show how the diverse projects at the Centre intersect through dialogue",
        "Supported a stakeholder with high aversion to change by presenting data to inform decisions and committing to testing new features to ensure they meet the organization's needs",
        "Developed a project plan for phase two of the redesign to continue improving site functionality and user experience",
        "Ensured site redesign incorporated accessibility standards",
        "Developed a content strategy to make use of new site features",
        "Developed a staff bio template to further show how each initiative relates back to dialogue",
        "Designed wireframes using Figma",
      ],
      outcomes:
        "The website redesign resulted in clearer understanding of organizational mission and improved access to resources.",
      nextStepsList: [
        "Conduct another round of user testing, focusing on the main audience, to gather data on the redesigned site and inform phase two requirements",
        "Research accessibility standards and audit redesigned pages to ensure compliance",
        "Finesse brand narrative content",
        "Develop and maintain a site manual to document processes and rationale",
      ],
      relatedProjectsList: [],
      SupportingLinksList: [
        {
          urlName: "Figma",
          url: "https://www.figma.com/design/FGzXzHSoMXff4taUFWdWWN/CLF4-Redesign",
        },
      ],
    },
  ];
  
  // {
  //     id: "",
  //     projectName: "",
  //     projectURL: "",
  //     status: "",
  //     type: "",
  //     client: "",
  //     role: "",
  //     collaborators: "",
  //     launchDate: "",
  //     topSkills: "",
  //     skills: "",
  //     challenge: "",
  //     solution: "",
  //     roleIntro: "",
  //     roleList: "",
  //     outcomes: "",
  //     nextStepsList: "",
  //     relatedProjectsList: "",
  //     SupportingLinksList: "",
  // },
  
  //     {
  //       id: "",
  //       name: "",
  //       role: "",
  //       company: "",
  //       year: "2024",
  //       urlText: "sfu.ca/dialogue",
  //       url: "",
  //       imgURL: require("../../assets/images/portfolio-tb-sfu-website.png"),
  //       topSkills: "",
  //       skills: ["HTML", "Graphic Design", "Product Management", "Project Management", "Web Design"]
  //     },
  //     {
  //         id: "BEF61A45-A31F-4441-887F-3E0BBB2BAFE3",
  //         role: "Creator",
  //         name: "Challenge Accepted App",
  //         company: "BrainStation Capstone",
  //         year: "2023",
  //         urlText: "github.com/stephlyanie/challenge-accepted-gui",
  //         url: "https://github.com/stephlyanie/challenge-accepted-gui",
  //         imgURL: require("../../assets/images/portfolio-tb-ca-website.png"),
  //         topSkills: "mySQL | Javascript | React",
  //         skills: ["Figma", "mySQL", "JavaScript", "React", "UI Development"]
  //     },
  //     {
  //         id: "CBDCA935-345D-4C92-A04E-EFCB8E9C43A7",
  //         role: "Web Designer",
  //         name: "Maple Counselling Website",
  //         company: "Freelance",
  //         year: "2021",
  //         urlText: "maplecounselling.ca",
  //         url: "https://www.maplecounselling.ca/",
  //         imgURL: require("../../assets/images/portfolio-tb-mc-website.png"),
  //         topSkills: "CSS | HTML | WordPress",
  //         skills: ["CSS", "HTML", "Product Management", "Web Design", "WordPress"]
  //     },
  //     {
  //         id: "F40384B2-935D-4419-A156-0ED2585009C3",
  //         role: "Project Manager and Designer",
  //         name: "Being Safe, Being Me",
  //         company: "SARAVYC at UBC",
  //         year: "2019",
  //         urlText: "saravyc.ubc.ca/ctyhs2019/",
  //         url: "https://www.saravyc.ubc.ca/ctyhs2019/",
  //         imgURL: require("../../assets/images/portfolio-tb-ctyhs-website.png"),
  //         topSkills: "CSS | HTML | WordPress",
  //         skills: ["CSS", "HTML", "Graphic Design", "Marketing Strategy", "Project Management", "Web Design", "WordPress"]
  //     },
  //     {
  //         id: "30612E1A-81F4-40E0-858C-CCC84AA7868A",
  //         role: "Project Manager and Designer",
  //         name: "Out at Home",
  //         company: "SARAVYC at UBC",
  //         year: "2019",
  //         urlText: "saravyc.ubc.ca/outathome/",
  //         url: "https://www.saravyc.ubc.ca/outathome/",
  //         imgURL: require("../../assets/images/portfolio-tb-oah-website.png"),
  //         topSkills: "CSS | HTML | WordPress",
  //         skills: ["CSS", "HTML", "Graphic Design", "Marketing Strategy", "Project Management", "Web Design", "WordPress"]
  //     }
  // ]