export const projectList = [
  {
    id: "sfu-website-redesign",
    projectName: "SFU Centre for Dialogue Website Redesign",
    projectURL: "https://www.sfu.ca/dialogue.html",
    imgURL: require("../assets/images/portfolio-tb-sfu-website.png"),
    status: "Phase One Complete, Phase Two In Progress",
    type: "Employee",
    client: "SFU Morris J. Wosk Centre for Dialogue",
    role: "Product Manager and Designer",
    launchDate: "Feb. 15, 2024",
    topSkills: "HTML | Product Management | UI Design",
    skills: [
      "HTML",
      "Product Management",
      "UI Design",
      "Team Leadership",
      "User Testing",
      "Cross-team Collaboration",
      "Change Management",
      "Training",
      "Technical Writing",
      "Project Management",
      "W3C Standards",
      "Brand Narrative",
      "Web Strategy",
      "Content Strategy",
    ],
    challenge:
      "The Centre for Dialogue underwent a period of rapid growth. A side effect of this growth was that the brand narrative had not kept up with the complexity of projects and achievements throughout the Centre. One of the ways this challenge manifested itself publicly was through the website, which had unclear user journeys to understand the Centre's mission for its various audiences.",
    solution:
      "To address this challenge, I initiated a website redesign informed by user testing.",
    roleIntro:
      "My role was to plan and lead the project through to completion.",
    roleList: [
      "Convened several stakeholder meetings throughout the process to build project buy-in, collect functionality requests, and manage expectations",
      "Developed the user testing framework to inform the redesign requirements",
      "Consolidated functionality requests and user testing input to prioritize revisions and present solutions to the executive team",
      "Created the revised site-map based on stakeholder meetings and user testing to improve user experience and overall brand trust",
      "Prioritized and delegated tasks among the communications team to execute the redesign",
      "Designed and implemented several site sections (notably the search for resources, dialogue approaches, what is dialogue, K&P, and signature events sections) to move the process forward while the team juggled several other responsibilities",
      "Envisioned and implemented cross-promotional features to encourage deeper engagement with the site's content and to  show how the diverse projects at the Centre intersect through dialogue",
      "Supported a stakeholder with high aversion to change by presenting data to inform decisions and committing to testing new features to ensure they meet the organization's needs",
      "Developed a project plan for phase two of the redesign to continue improving site functionality and user experience",
      "Ensured site redesign incorporated accessibility standards",
      "Developed a content strategy to make use of new site features",
      "Developed a staff bio template to further show how each initiative relates back to dialogue",
      "Designed wireframes using Figma",
    ],
    outcomes:
      "The website redesign resulted in clearer understanding of organizational mission and improved access to resources.",
    nextStepsList: [
      "Conduct another round of user testing, focusing on the main audience, to gather data on the redesigned site and inform phase two requirements",
      "Research accessibility standards and audit redesigned pages to ensure compliance",
      "Finesse brand narrative content",
      "Develop and maintain a site manual to document processes and rationale",
    ],
    relatedProjectsList: [],
    supportingLinksList: [
      {
        urlName: "Figma Wireframes",
        url: "https://www.figma.com/design/FGzXzHSoMXff4taUFWdWWN/CLF4-Redesign",
      },
    ],
  },
  {
    id: "challenge-accepted",
    projectName: "Challenge Accepted App",
    projectURL: "https://github.com/stephlyanie/challenge-accepted-gui",
    status: "Preparing to Launch",
    type: "Personal",
    client: "BrainStation Capstone Project",
    role: "Creator",
    launchDate: "TBD",
    topSkills: "mySQL, Node JS, React",
    skills: ["mySQL", "Node JS", "React", "JavaScript"],
    challenge:
      "As the final project for the BrainStation software engineering diploma, we were tasked with the challenge of creating a full stack app.",
    solution:
      "Inspired by the Great Canadian Baking Show, I developed the “Challenge Accepted” app where users can share and discover various types of baking creations and challenges.",
    roleIntro:
      "My role was to conceptualize, design, and develop this full stack app.",
    roleList: [
      "Designed UI using Figma",
      "Developed brand guidelines",
      "Developed front-end using React",
      "Developed back-end using Node",
      "Created database in mySQL",
    ],
    outcomes: "The app will be launched this summer.",
    nextStepsList: [
      "Launch using Heroku and Netlify",
      "Refine the UI using Joy UI",
      "Add more categories",
      "Implement more interactivity such as liking and commenting",
    ],
    relatedProjectsList: "",
    supportingLinksList: [
      {
        urlName: "Figma Wireframes",
        url: "",
      },
    ],
  }, {
        id: "maple-counselling-website",
        projectName: "Maple Counselling Website",
        projectURL: "https://www.maplecounselling.ca/",
        status: "Complete",
        type: "Freelance",
        client: "Maple Counselling",
        role: "Web Designer",
        launchDate: "March 2021",
        topSkills: "CSS | HTML | WordPress",
        skills: [
          "CSS", 
          "HTML", 
          "WordPress", 
          "Client Management",
        ],
        challenge: "Jane Whitlaw approached me to design a website to help her launch her counselling practice in South Surrey.",
        solution: "I worked with Jane to customize a WordPress site using a pre-made theme.",
        roleIntro: "My role was to create the site within the theme and customize pages to the client’s requests.",
        roleList: [
          "Designed all pages within the theme",
          "Customized pages using HTML and CSS",
          "Advised client on content needs and structure",
          "Implemented widgets to support site requirements",
          "Managed expectations of what's achievable within a small budget",
          "Launched site",
        ],
        outcomes: "The site was successfully launched and continues to contribute to the client's successful counselling practice.",
        nextStepsList: "",
        relatedProjectsList: "",
        supportingLinksList: [],
    }, {
          id: "saravyc-being-safe-being-me",
          projectName: "Being Safe, Being Me 2019",
          projectURL: "https://www.saravyc.ubc.ca/ctyhs2019/ ",
          status: "Complete",
          type: "Employee",
          client: "SARAVYC at UBC",
          role: "Designer and Writer",
          launchDate: "Nov. 16, 2020",
          topSkills: "CSS | UI Design | Graphic Design",
          skills: [
            "CSS, 
            "HTML", 
            "WordPress", 
            "Knowledge Mobilization", 
            "Graphic Design", 
            "Strategic Communications", 
            "Content Strategy", 
            "Video Producing", 
            "Script Writing", 
            "Advisory Groups", 
            "Professional Writing", 
            "Technical Writing", 
            "Key Messaging", 
            "Adobe InDesign", 
            "Adobe Illustrator", 
            "Adobe Photoshop", 
            "Social Media",
          ],
          challenge: "In 2019, SARAVYC at UBC launched their findings from the Canadian Trans and Non-binary Youth Health Survey. In addition to academic articles and presentations, the researchers wanted their findings to be accessible to a wide audience.",
          solution: "To mobilize these findings to a public audience, we developed the Being Safe, Being Me 2019 report and accompanying resources.",
          roleIntro: "My role was to write the report based on data aggregated by researchers, design the report and accompanying resources, and create a launch strategy. ",
          roleList: [
            "Wrote report content based on data aggregated by the researchers",
            "Designed the report using Adobe inDesign and report charts and graphs using Adobe Illustrator",
            "Designed seven regional fact sheet infographics using Adobe Illustrator",
            "Wrote scripts and project managed creation of four informational animated videos, which were created by Art Over Matter",
            "Designed the report’s landing page in UBC’s WordPress platform and customized pages using CSS and HTML",
            "Created and executed a content strategy to launch the report and share findings on social media",
            "Wrote a press release to support UBC’s media team in developing story pitches",
            "Facilitated translation into French and added the French content into all materials",
            "Created and revised all materials based on feedback from trans and non-binary youth advisory groups across the country",
          ],
          outcomes: "The report was launched in November 2020.",
          nextStepsList: "",
          relatedProjectsList: "",
          supportingLinksList: [],
      }, {
        id: "saravyc-out-at-home",
        projectName: "Out at Home",
        projectURL: "https://www.saravyc.ubc.ca/outathome/",
        status: "Complete",
        type: "Employee",
        client: "SARAVYC at UBC",
        role: "Designer and Writer",
        launchDate: "Oct 2019",
        topSkills: "CSS | UI Design | Graphic Design",
        skills: [
          "CSS", 
          "HTML", 
          "WordPress", 
          "Knowledge Mobilization", 
          "Graphic Design", 
          "Strategic Communications", 
          "Content Strategy", 
          "Video Producing", 
          "Script Writing", 
          "Advisory Groups", 
          "Professional Writing", 
          "Technical Writing", 
          "Key Messaging", 
          "Adobe InDesign", 
          "Adobe Illustrator", 
          "Adobe Photoshop", 
          "Social Media",
        ],
        challenge: "In 2019, SARAVYC at UBC was ready to mobilize their research findings to East Asian families in British Columbia.",
        solution: "Based on feedback from an East Asian parents advisory group, we created a take-home brochure, a website landing page, and three informational animated videos, all of which were then translated into four languages.",
        roleIntro: "My role was to write the content and design the materials.",
        roleList: [
          "Wrote report content based on data aggregated by the researchers",
          "Wrote brochure and website content based on data aggregated by the researchers",
          "Designed the brochure and supporting social media graphics using Adobe inDesign and report charts and graphs using Adobe Illustrator",
          "Designed seven regional fact sheet infographics using Adobe Illustrator",
          "Wrote scripts and project managed creation of three informational animated videos, which were created by Linnea Ritland",
          "Designed the report’s landing page in UBC’s WordPress platform and customized pages using CSS and HTML",
          "Created and executed a content strategy to launch the materials and share findings on social media",
          "Facilitated translation into four languages and added the translated content into all materials",
          "Created and revised all materials based on feedback from the advisory group",
        ],
        outcomes: "he materials were launched in October 2019. One of the collaborating researchers shared with me that this was the first time they’d seen supportive, research-based resources for LGBTQ+ youth written in their native language.",
        nextStepsList: "",
        relatedProjectsList: "",
        supportingLinksList: [],
    },
];

// {
//     id: "",
//     projectName: "",
//     projectURL: "",
//     status: "",
//     type: "",
//     client: "",
//     role: "",
//     launchDate: "",
//     topSkills: "",
//     skills: ["",],
//     challenge: "",
//     solution: "",
//     roleIntro: "",
//     roleList: ["",],
//     outcomes: "",
//     nextStepsList: "",
//     relatedProjectsList: "",
//     supportingLinksList: [
//       {
//         urlName: "",
//         url: "",
//       },
//     ],
// },
